### Amazon Kindle Review Sentiment Analysis

##### About dataset:

Context :

This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content:

5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.
Columns

- asin - ID of the product, like B000FA64PK
- helpful - helpfulness rating of the review - example: 2/3.
- overall - rating of the product.
- reviewText - text of the review (heading).
- reviewTime - time of the review (raw).
- reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
- reviewerName - name of the reviewer.
- summary - summary of the review (description).
- unixReviewTime - unix timestamp.

In [7]:
#importing libraries

import numpy as np
import pandas as pd

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [12]:
#importing dataset into dataframe

df = pd.read_csv("datasets\\all_kindle_review .csv")
df.head()

   Unnamed: 0.1  Unnamed: 0  ...                   summary unixReviewTime
0             0       11539  ...  Entertaining But Average     1283385600
1             1        5957  ...   Terrific menage scenes!     1381190400
2             2        9146  ...          Snapdragon Alley     1397174400
3             3        7038  ...    very light murder cozy     1404518400
4             4        1776  ...                      Book     1356912000

[5 rows x 11 columns]

In [14]:
#discarding other columns

df = df[['rating', 'reviewText']]
df.head()

   rating                                         reviewText
0       3  Jace Rankin may be short, but he's nothing to ...
1       5  Great short read.  I didn't want to put it dow...
2       3  I'll start by saying this is the first of four...
3       3  Aggie is Angela Lansbury who carries pocketboo...
4       4  I did not expect this type of book to be in li...

In [15]:
#checking for null values or duplicates

df.isnull().sum()

rating        0
reviewText    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
#analyzing rating column

df['rating'].unique()

array([3, 5, 4, 2, 1])

In [18]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [20]:
#changing data in rating column to binary values
#rating less than 3 as 0 and greater than 3 as 1.

df['rating']=df['rating'].apply(lambda x: 0 if x < 3 else 1)

In [21]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [22]:
#text preprocessing on reviewText column

#converting into lower case

df['reviewText'] = df['reviewText'].str.lower()

In [23]:
df['reviewText']

0        jace rankin may be short, but he's nothing to ...
1        great short read.  i didn't want to put it dow...
2        i'll start by saying this is the first of four...
3        aggie is angela lansbury who carries pocketboo...
4        i did not expect this type of book to be in li...
                               ...
11995    valentine cupid is a vampire- jena and ian ano...
11996    i have read all seven books in this series. ap...
11997    this book really just wasn't my cuppa.  the si...
11998    tried to use it to charge my kindle, it didn't...
11999    taking instruction is a look into the often hi...
Name: reviewText, Length: 12000, dtype: str